project = "playground-s-11-c5f4c261"
region     = "us-central1"
zone       = "us-central1-c"
vpc_name = "dt-vpc"
subnetwork_name = "dt-subnet"
cluster_name = "dt-private-cluster"
credentials_file = "/Users/ajay.krishna/Downloads/playground-s-11-c5f4c261-082640599a07.json"